name: movefy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/google_logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4285F4"